name: Create Tag

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Klemensas/action-autotag@stable
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          tag_prefix: "v"
      - name: Checkout code
        run: |
          git config --local user.email "lricardo@outlook.com"
          git config --local user.name "Luiz Ricardo"
          git tag -a v${{ package.json.version }} -m "Release v${{ package.json.version }}"
      - name: Push Tag
        run: git push origin v${{ package.json.version }}
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create changelog
        id: changelog
        uses: loopwerk/tag-changelog@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          exclude_types: other,doc,chore

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ package.json.version }}
          release_name: Release v${{ package.json.version }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
